on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
name: Deploy website on push
jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.iwebsecurities.com
        username: salesanta.com@salesanta.com
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        port: 21 # todo replace with your web hosts ftps port
